 
 CREATE TABLE DEPT (
     DEPTNO NUMBER PRIMARY KEY,
     D_NAME VARCHAR2(20) );


CREATE TABLE EMP (
     EMPNO NUMBER PRIMARY KEY,
     ENAME VARCHAR2(20),
     GENDER VARCHAR2(8),
     DEPTNO NUMBER,
     DOJ DATE,
     SALARY NUMBER,
     STATUS VARCHAR2(20),
     FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO));




CREATE TABLE ATTRITION (
    EMPNO NUMBER,
    ATTRITION_REASON VARCHAR2(50),
    NOTICE_PERIOD NUMBER,
    LAST_WORKING_DATE DATE,
    FOREIGN KEY (EMPNO) REFERENCES EMP(EMPNO));